import { useState, createContext } from 'react';
import Head from 'next/head'
import fractal from '@couds/fractal-react';

const Context = createContext({ contextValue: '' });

export default function Home({ ssr }: { ssr: any}) {
  const [mount, setMount] = useState(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <fractal _setup={{
            script: '//localhost:3003/static/microfrontend-ssr-frameworkless.js',
            markup: ssr.markup,
            mount: true,
          }}
          {...ssr.initialState}
        />
        <button onClick={() => setMount(!mount)}>Toggle mount the MF again</button>
        {
          mount && (
            <Context.Provider value={{ contextValue: 'test' }}>
              <fractal _setup={{
                script: '//localhost:3003/static/microfrontend-ssr-frameworkless.js',
                mount: true,
              }}
              name="dynamic =)"
              text="I was conditional render from client"
              onClick={() => { alert('Callback from host app') }}
              Context={Context}
            />
          </Context.Provider>
          )
        }
      </main>
    </>
  )
}
