name: PR Cleanup

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
    branches: [main]
  workflow_dispatch:
    inputs:
      stage:
        type: string
        required: true

permissions:
  contents: read
  id-token: write
  pull-requests: read
  packages: write

jobs:
  clean-up:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.stage || format('pr-{0}', github.event.number) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Remove packages
      uses: couds/github-actions/actions/remove-npm-package@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        version: ${{ env.VERSION }}
        packages: |
          ["fractal-core", "fractal-cli", "fractal-react"]
